### ISSUE TITLE
Cannot read property 'replace' of undefined 

### ISSUE THREAD

**Issue by dmitrii-snytkin** [phonegap/ios-sim#212] opened 2017-06-14 08:53 UTC
When i run `cordova run ios --list` i get error (cordova 7.0.1)

```
TypeError: Cannot read property 'replace' of undefined
    at remove (/Users/dmitry/projects/newApp/platforms/ios/cordova/node_modules/ios-sim/src/lib.js:282:70)
    at Array.forEach (native)
    at Object.getdevicetypes (/Users/dmitry/projects/newApp/platforms/ios/cordova/node_modules/ios-sim/src/lib.js:292:22)
    at listEmulatorImages (/Users/dmitry/projects/newApp/platforms/ios/cordova/lib/list-emulator-images:34:29)
    at Object.<anonymous> (/Users/dmitry/projects/newApp/platforms/ios/cordova/lib/list-emulator-images:43:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
Apparently, it's the same problem as [here](https://stackoverflow.com/questions/42350505/error-cannot-read-property-replace-of-undefined-when-building-ios-cordova).

**Comment by Hirbod** [comment] 2017-06-14 11:09
I got the same issue, a quick workaround:

```bash
cd platforms/ios/cordova/node_modules/
sudo npm install ios-sim@latest
```

**Comment by shazron** [comment] 2017-06-14 19:32
Duplicate of #210

**Closed by shazron** 2017-06-14 19:32 UTC
